In [1]:
import numpy as np

In [89]:
one=np.array([2,14,54,67,8])
one.argmax() #gives the index of the maximum value.

3

In [91]:
one.argmin()

0

In [93]:
one.argsort() #sorts the specified array in ascending order on the basis of index not by element itself.

array([0, 4, 1, 2, 3], dtype=int64)

In [95]:
one.argsort()[::-1] # in descending order on the basis of index.

array([3, 2, 1, 4, 0], dtype=int64)

In [101]:
np.sort(one) # Sorting by element.

array([ 2,  8, 14, 54, 67])

In [103]:
np.sort(one)[::-1] # sorting in descending order by element itself.

array([67, 54, 14,  8,  2])

In [111]:
x=[[11,2,3],[45,50,6],[7,8,9]]
ar=np.array(x)
print(np.shape(ar))
ar

(3, 3)


array([[11,  2,  3],
       [45, 50,  6],
       [ 7,  8,  9]])

In [113]:
ar=np.array([[2,3,4],
             [7,6,5],
             [1,8,9]]) 

In [115]:
ar.argsort(axis=1) #sorted on the basis of ROWS.here ,it sorts the index value.

array([[0, 1, 2],
       [2, 1, 0],
       [0, 1, 2]], dtype=int64)

In [117]:
ar.argsort(axis=0)# on the basis of columns.

array([[2, 0, 0],
       [0, 1, 1],
       [1, 2, 2]], dtype=int64)

In [121]:
arr1=[[1,6,7],[1,4,3]]
print(np.shape(arr1))
print(np.shape(ar))
ar

(2, 3)
(3, 3)


array([[2, 3, 4],
       [7, 6, 5],
       [1, 8, 9]])

In [10]:
ar.argmin() #smallest value at index 6....1

6

In [11]:
ar.argmax() #highest value at index 8....9

8

In [12]:
ar.argmax(axis=0) # axis 0 refers to vertical axis.

array([1, 2, 2], dtype=int64)

In [13]:
ar.argmax(axis=1) # axis 1 refers to horizontal axis.

array([2, 0, 2], dtype=int64)

In [14]:
ar

array([[2, 3, 4],
       [7, 6, 5],
       [1, 8, 9]])

In [15]:
ar.argsort() #by default it takes axis 1(ROW) and sorts them by their indexes in ascending order.

array([[0, 1, 2],
       [2, 1, 0],
       [0, 1, 2]], dtype=int64)

In [16]:
ar.argsort(axis=0)

array([[2, 0, 0],
       [0, 1, 1],
       [1, 2, 2]], dtype=int64)

In [17]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 1, 2]], dtype=int64)

In [18]:
ar

array([[2, 3, 4],
       [7, 6, 5],
       [1, 8, 9]])

In [19]:
ar.ravel() # to flatten the multi-dimensional array into a 1-D array.

array([2, 3, 4, 7, 6, 5, 1, 8, 9])

In [20]:
ar.reshape(1,9) # 1 row,9 col. # you can add or remove the dimensions from an array according to our needs.

array([[2, 3, 4, 7, 6, 5, 1, 8, 9]])

In [21]:
ar.reshape(9,1) #9 row, 1 col.

array([[2],
       [3],
       [4],
       [7],
       [6],
       [5],
       [1],
       [8],
       [9]])

In [22]:
arr1=np.array([[1,2,3],[1,2,3],[1,2,3]])
arr1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [23]:
ar + arr1 #adds 2 arrays with same Row and Col.

array([[ 3,  5,  7],
       [ 8,  8,  8],
       [ 2, 10, 12]])

In [24]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.73205081]])

In [25]:
arr1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [26]:
arr1.argmin() #returns the index of minimum value.

0

In [27]:
arr1.min() #returns the smallest value itself.

1

In [28]:
np.where(arr1>2) # Both arrays are co-related, R/C=0/2,1/2,2/2.

(array([0, 1, 2], dtype=int64), array([2, 2, 2], dtype=int64))

In [29]:
arr1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [30]:
arr2=np.array([[1,2,3],[4,5,6],[7,1,0]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [31]:
np.where(arr2>3) # again, R/C=1/0,1/1,1/2,2/0.

(array([1, 1, 1, 2], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [32]:
np.where(arr2>2)

(array([0, 1, 1, 1, 2], dtype=int64), array([2, 0, 1, 2, 0], dtype=int64))

In [33]:
type(np.where(arr2>5)) #returns the type of the object. here it is tuple.

tuple

In [34]:
np.count_nonzero(arr2)

8

In [35]:
import sys # sys is a python's standard library used to control program's exit behaviour and handle command line arguments. 

In [36]:
pytar=[1,3,5,7]
npar=np.array(pytar) # converting the pytar list into numpy array.

In [37]:
sys.getsizeof(1)* len(pytar)

112

In [38]:
npar.itemsize*npar.size

16

# numpy arrays use contigeous memory and they are more memory efficient than that of python as they only store homogeneous data type(single dATA type).